# user string params
LEN_USERNAME_MIN = 3
LEN_USERNAME_MAX = 16
LEN_EMAIL_MIN = 3
LEN_EMAIL_MAX = 64
LEN_PASSWORD_PLAIN_MIN = 12
LEN_PASSWORD_PLAIN_MAX = 128
LEN_NAME_FIRST_MIN = 3
LEN_NAME_FIRST_MAX = 32
LEN_NAME_LAST_MIN = 3
LEN_NAME_LAST_MAX = 32
LEN_PASSWORD_MIN = 12
LEN_PASSWORD_ARGON2 = 256
LEN_VERIFICATION_TOKEN_HASH = 64
MINUTES_EMAIL_VERIFICATION_TOKEN_EXPIRE = 60
SMTP_TIMEOUT_SECONDS = 10

# auth rate limiting
SIGNUP_RATE_LIMIT_WINDOW_SECONDS = 1 # CHANGE
SIGNUP_RATE_LIMIT_MAX_ATTEMPTS_PER_IP = 999 # CHANGE
SIGNUP_RATE_LIMIT_MAX_ATTEMPTS_PER_IDENTITY = 999 # CHANGE

# rfc string params
LEN_RFC_TITLE_MIN = 8
LEN_RFC_TITLE_MAX = 64
LEN_RFC_SLUG_MIN = 4
LEN_RFC_SLUG_MAX = 32
LEN_RFC_STATUS_MAX = 16
LEN_RFC_CONTENT_MIN = 8
LEN_RFC_CONTENT_MAX = 65536
LEN_RFC_SUMMARY_MIN = 8
LEN_RFC_SUMMARY_MAX = 256

# comment string params
LEN_COMMENT_CONTENT_MIN = 4
LEN_COMMENT_CONTENT_MAX = 4096

# agent contributor params
LEN_CONTRIB_AGENT_NAME_MIN = 1
LEN_CONTRIB_AGENT_NAME_MAX = 32
LEN_CONTRIB_HOST_NAME_MIN = 1
LEN_CONTRIB_HOST_NAME_MAX = 32

# revision params
LEN_REVISION_MSG_MIN = 4
LEN_REVISION_MSG_MAX = 256
