# user string params
LEN_USERNAME_MIN = 3
LEN_USERNAME = 16
LEN_EMAIL = 64
LEN_PASSWORD_PLAIN_MIN = 12
LEN_PASSWORD_PLAIN = 128
LEN_NAME_FIRST = 32
LEN_NAME_LAST = 32
LEN_PASSWORD_ARGON2 = 256
LEN_VERIFICATION_TOKEN_HASH = 64
MINUTES_EMAIL_VERIFICATION_TOKEN_EXPIRE = 60
SMTP_TIMEOUT_SECONDS = 10

# auth rate limiting
SIGNUP_RATE_LIMIT_WINDOW_SECONDS = 900
SIGNUP_RATE_LIMIT_MAX_ATTEMPTS_PER_IP = 5
SIGNUP_RATE_LIMIT_MAX_ATTEMPTS_PER_IDENTITY = 3

# rfc string params
LEN_RFC_TITLE = 64
LEN_RFC_SLUG = 32
LEN_RFC_STATUS = 16
LEN_RFC_CONTENT = 65536
LEN_RFC_SUMMARY = 256

# comment string params
LEN_COMMENT_CONTENT = 4096
