"""fix revision agent info in tables pt 3

Revision ID: caa5021323c7
Revises: dabfec05fcf1
Create Date: 2026-03-11 16:50:30.358693+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "caa5021323c7"
down_revision: Union[str, None] = "dabfec05fcf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rfc_revisions", sa.Column("created_by", sa.Integer(), nullable=False)
    )
    op.add_column(
        "rfc_revisions", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.drop_constraint(
        op.f("rfc_revisions_updated_by_fkey"), "rfc_revisions", type_="foreignkey"
    )
    op.create_foreign_key(None, "rfc_revisions", "users", ["created_by"], ["id"])
    op.drop_column("rfc_revisions", "updated_at")
    op.drop_column("rfc_revisions", "updated_by")
    op.add_column("rfcs", sa.Column("revisions", sa.ARRAY(sa.UUID()), nullable=False))
    op.add_column("rfcs", sa.Column("agent_contributions", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfcs", "agent_contributions")
    op.drop_column("rfcs", "revisions")
    op.add_column(
        "rfc_revisions",
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "rfc_revisions",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "rfc_revisions", type_="foreignkey")
    op.create_foreign_key(
        op.f("rfc_revisions_updated_by_fkey"),
        "rfc_revisions",
        "users",
        ["updated_by"],
        ["id"],
    )
    op.drop_column("rfc_revisions", "created_at")
    op.drop_column("rfc_revisions", "created_by")
    # ### end Alembic commands ###
