"""update users table

Revision ID: cf30aef8d9b6
Revises: c271fd63e1c9
Create Date: 2026-02-25 19:10:46.823675+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf30aef8d9b6'
down_revision: Union[str, None] = 'c271fd63e1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_argon2', sa.String(length=64), nullable=False))
    op.drop_column('users', 'password_sha256')
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_argon2')
    # ### end Alembic commands ###
