"""added review info on rfcs table

Revision ID: 67d3110610bf
Revises: 4e3d92f15423
Create Date: 2026-03-23 18:33:57.518967+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67d3110610bf"
down_revision: Union[str, None] = "4e3d92f15423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rfcs", sa.Column("review_requested", sa.Boolean(), nullable=True))
    op.add_column("rfcs", sa.Column("is_reviewed", sa.Boolean(), nullable=True))
    op.add_column(
        "rfcs", sa.Column("review_reason", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfcs", "review_reason")
    op.drop_column("rfcs", "is_reviewed")
    op.drop_column("rfcs", "review_requested")
    # ### end Alembic commands ###
