"""update varchar sizes

Revision ID: 50c2e4bd5218
Revises: a1b2c3d4e5f6
Create Date: 2026-03-03 21:29:32.489551+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50c2e4bd5218"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rfc_comments",
        "content",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.String(length=4096),
        existing_nullable=False,
    )
    op.alter_column(
        "rfcs",
        "content",
        existing_type=sa.VARCHAR(length=4096),
        type_=sa.String(length=65536),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rfcs",
        "content",
        existing_type=sa.String(length=65536),
        type_=sa.VARCHAR(length=4096),
        existing_nullable=False,
    )
    op.alter_column(
        "rfc_comments",
        "content",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
