"""add revision support

Revision ID: dabfec05fcf1
Revises: 9f4c2d1a7b6e
Create Date: 2026-03-11 16:26:50.388487+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabfec05fcf1'
down_revision: Union[str, None] = '9f4c2d1a7b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfc_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfc_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('agent_contributors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=65536), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['rfc_id'], ['rfcs.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rfcs', sa.Column('current_revision', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'rfcs', 'rfc_revisions', ['current_revision'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_users_email_lower_unique'), table_name='users')
    op.drop_index(op.f('ix_users_username_lower_unique'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username_lower_unique'), 'users', [sa.literal_column('lower(username::text)')], unique=True)
    op.create_index(op.f('ix_users_email_lower_unique'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'rfcs', type_='foreignkey')
    op.drop_column('rfcs', 'current_revision')
    op.drop_table('rfc_revisions')
    # ### end Alembic commands ###
