"""add summary content in table rfcs

Revision ID: 688e93511f44
Revises: ed52c23b8301
Create Date: 2026-02-26 20:40:09.207874+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688e93511f44'
down_revision: Union[str, None] = 'ed52c23b8301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfcs', sa.Column('summary', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfcs', 'summary')
    # ### end Alembic commands ###
