"""added public bool to RFCs

Revision ID: 5a8afb8dfde1
Revises: 5bebd2f72b04
Create Date: 2026-03-13 21:32:09.559007+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a8afb8dfde1"
down_revision: Union[str, None] = "5bebd2f72b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rfc_revisions", sa.Column("is_public", sa.Boolean(), nullable=True))
    op.add_column("rfcs", sa.Column("is_public", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfcs", "is_public")
    op.drop_column("rfc_revisions", "is_public")
    # ### end Alembic commands ###
