"""add support for quarantine

Revision ID: ae31294efd38
Revises: 5a8afb8dfde1
Create Date: 2026-03-14 02:16:54.263198+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae31294efd38"
down_revision: Union[str, None] = "5a8afb8dfde1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quarantined_rfcs",
        sa.Column("quarantine_id", sa.Integer(), nullable=False),
        sa.Column("quarantined_by", sa.Integer(), nullable=False),
        sa.Column("quarantined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=2048), nullable=False),
        sa.Column("rfc_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quarantined_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rfc_id"],
            ["rfcs.id"],
        ),
        sa.PrimaryKeyConstraint("quarantine_id"),
    )
    op.create_table(
        "quarantined_comments",
        sa.Column("quarantine_id", sa.Integer(), nullable=False),
        sa.Column("quarantined_by", sa.Integer(), nullable=False),
        sa.Column("quarantined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=2048), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["rfc_comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quarantined_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("quarantine_id"),
    )
    op.add_column(
        "rfc_comments", sa.Column("is_quarantined", sa.Boolean(), nullable=True)
    )
    op.add_column("rfcs", sa.Column("is_quarantined", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfcs", "is_quarantined")
    op.drop_column("rfc_comments", "is_quarantined")
    op.drop_table("quarantined_comments")
    op.drop_table("quarantined_rfcs")
    # ### end Alembic commands ###
