"""add more fields to users and rfcs

Revision ID: d6e1433da3ba
Revises: 50c2e4bd5218
Create Date: 2026-03-03 22:08:03.051034+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6e1433da3ba"
down_revision: Union[str, None] = "50c2e4bd5218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rfcs", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("rfcs", sa.Column("title", sa.String(length=64), nullable=False))
    op.add_column("rfcs", sa.Column("slug", sa.String(length=32), nullable=False))
    op.add_column("rfcs", sa.Column("status", sa.String(length=16), nullable=False))
    op.add_column("users", sa.Column("name_last", sa.String(length=32), nullable=False))
    op.add_column(
        "users", sa.Column("name_first", sa.String(length=32), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name_first")
    op.drop_column("users", "name_last")
    op.drop_column("rfcs", "status")
    op.drop_column("rfcs", "slug")
    op.drop_column("rfcs", "title")
    op.drop_column("rfcs", "updated_at")
    # ### end Alembic commands ###
