"""added table readme_revisions

Revision ID: 4e3d92f15423
Revises: ae31294efd38
Create Date: 2026-03-19 21:33:28.790899+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e3d92f15423"
down_revision: Union[str, None] = "ae31294efd38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readme_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content", sa.String(length=65536), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("reason", sa.String(length=2048), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("readme_revisions")
    # ### end Alembic commands ###
