"""added parent_id to table rfc_comments

Revision ID: 754f4d3232bb
Revises: 688e93511f44
Create Date: 2026-03-02 18:27:38.027990+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "754f4d3232bb"
down_revision: Union[str, None] = "688e93511f44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rfc_comments", sa.Column("parent_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rfc_comments", "parent_id")
    # ### end Alembic commands ###
